<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("test");
?><?$APPLICATION->IncludeComponent(
	"api:feedbackex", 
	"callback", 
	array(
		"COMPONENT_TEMPLATE" => "callback",
		"DISABLE_SEND_MAIL" => "N",
		"DISABLE_CHECK_SESSID" => "N",
		"REPLACE_FIELD_FROM" => "Y",
		"API_FEX_FORM_ID" => "feedback",
		"OK_TEXT" => "Сообщение успешно отправлено",
		"OK_TEXT_AFTER" => "Спасибо! Мы рассмотрим сообщение и обязательно свяжемся с Вами.<br>Пожалуйста, дождитесь ответа.",
		"EMAIL_TO" => "qwazik21@gmail.com",
		"BCC" => "",
		"CONFIG_PATH" => "",
		"DISPLAY_FIELDS" => array(
			0 => "TITLE",
			1 => "PHONE",
		),
		"REQUIRED_FIELDS" => array(
			0 => "PHONE",
		),
		"FORM_WIDTH" => "",
		"FORM_CLASS" => "",
		"TITLE_DISPLAY" => "Y",
		"FORM_TITLE" => "Обратный звонок",
		"FORM_TITLE_LEVEL" => "3",
		"FIELD_ERROR_MESS" => "#FIELD_NAME# обязательное",
		"EMAIL_ERROR_MESS" => "Указанный E-mail некорректен",
		"FORM_SUBMIT_CLASS" => "btn btn--min-width btn--sm btn--second-st",
		"FORM_SUBMIT_VALUE" => "Отправить",
		"FORM_SUBMIT_STYLE" => "",
		"HIDE_FIELD_NAME" => "Y",
		"HIDE_ASTERISK" => "N",
		"FORM_AUTOCOMPLETE" => "Y",
		"FIELD_SIZE" => "default",
		"FIELD_NAME_POSITION" => "stacked",
		"FORM_LABEL_TEXT_ALIGN" => "left",
		"FORM_LABEL_WIDTH" => "150px",
		"FORM_FIELD_WIDTH" => "",
		"FORM_TEXTAREA_ROWS" => "5",
		"MAIL_SUBJECT_ADMIN" => "#SITE_NAME#: Сообщение из формы обратной связи",
		"MAIL_SUBJECT_USER" => "#SITE_NAME#: Копия сообщения из формы обратной связи",
		"MAIL_SEND_USER" => "N",
		"WRITE_MESS_DIV_STYLE" => "padding:10px;border-bottom:1px dashed #dadada;",
		"WRITE_MESS_DIV_STYLE_NAME" => "font-weight:bold;",
		"WRITE_MESS_DIV_STYLE_VALUE" => "",
		"WRITE_MESS_FILDES_TABLE" => "N",
		"WRITE_MESS_TABLE_STYLE" => "border-collapse: collapse; border-spacing: 0;",
		"WRITE_MESS_TABLE_STYLE_NAME" => "max-width: 200px; color: #848484; vertical-align: middle; padding: 5px 30px 5px 0px; border-bottom: 1px solid #e0e0e0; border-top: 1px solid #e0e0e0;",
		"WRITE_MESS_TABLE_STYLE_VALUE" => "vertical-align: middle; padding: 5px 30px 5px 0px; border-bottom: 1px solid #e0e0e0; border-top: 1px solid #e0e0e0;",
		"USE_JQUERY" => "N",
		"USE_PLACEHOLDER" => "N",
		"USE_AUTOSIZE" => "N",
		"USE_FLATPICKR" => "N",
		"USE_SCROLL" => "N",
		"SCROLL_SPEED" => "1000",
		"PAGE_TITLE" => "",
		"PAGE_URL" => "",
		"DIR_URL" => "",
		"DATETIME" => "",
		"USE_MODAL" => "N",
		"USE_EULA" => "N",
		"USE_PRIVACY" => "N",
		"THEME" => "gradient",
		"COLOR" => "default"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>